### ISSUE TITLE
Mention GeoStats.jl for n-dimensional GP?

### ISSUE THREAD

**Issue by juliohm** [ericagol/celerite.jl#24]
I am putting some effort to develop a package for high-performance geostatistics in Julia. One of the main algorithms is Kriging estimation, which is nothing more than a n-dimensional GP with a general distance metric: http://juliohm.github.io/GeoStats.jl/stable/estimation.html

If you feel that users of `celerite.jl` would benefit from `GeoStats.jl` in the n-dimensional case, it would be great to add a reference to it in the README :blush: 

Feel free to close the issue anytime, thanks for porting the celerite project to Julia.

**Comment by ericagol** [comment]
Thanks for letting me know - we have been trying to think of how to extend celerite to multiple dimensions.  What is the scaling of your technique with the dimensions of the problem?

**Comment by juliohm** [comment]
I don't have benchmarks for it, but in our applications the dimensions are usually 2D, 3D or at most 4D (space + time). Please let me know if you want to give the package a try, contributions are more than welcome. I have high-performance as one of my top priorities as well.

I am planning to write some tutorials in the next weeks to illustrate the capabilities of the package. My main goal is to have a general framework that can perform estimation/simulation on arbitrary domains that are not necessarily structured grids.

**Comment by juliohm** [comment]
I am closing this issue, thank you for the replies.
