### ISSUE TITLE
Implementing LAPACK solver

### ISSUE THREAD

**Issue by ericagol** [ericagol/celerite.jl#6]
When J > 4, should be faster to use LAPACK solver.  There are the gbtrf & gbtrs functions that are built into Julia, but also the MKS solver that may require recompiling Julia.

**Comment by dfm** [comment]
I've implemented this on my branch. You just do something like:

```julia
gp = celerite.Celerite(kernel, use_lapack=true)
```

to use it. I've tested that it gives the correct results but I haven't benchmarked.
