### ISSUE TITLE
Implementing Cholesky solver - cholesky branch

### ISSUE THREAD

**Issue by ericagol** [ericagol/celerite.jl#7]
Some new routines have been added which implement the Cholesky solver in Julia:

gp.jl:  This contains the subroutines and basic functionality - now includes simulation & prediction.

sturms_theorem.jl: Uses Sturm's theorem to check that kernel is positive definite.

Problem:  These routines are written with K = L L^T, rather than K = L D L^T, which is how the C++/Python versions were implemented.  These should be made consistent.

- [x] Rewrite as LDLT

- [x] Convert code to same format to be compatible with extended matrix formalism.

- [x] Figure out how to update celerite.jl package.

- [x] Finish developing cholesky branch, and merge with master branch.

**Comment by giordano** [comment]
What do you mean exactly by "Figure out how to update celerite.jl package"?

**Comment by ericagol** [comment]
@giordano I am having trouble using the celerite.jl module in my local repository.  Eventually I would also like to make this available as a Julia package, but I'm not sure how to do that yet.

**Comment by giordano** [comment]
> I am having trouble using the celerite.jl module in my local repository.

If you can give me more information, I can help you.

> Eventually I would also like to make this available as a Julia package, but I'm not sure how to do that yet.

The manual procedure to register and publish a package is described here: https://docs.julialang.org/en/stable/manual/packages/#tagging-and-publishing-your-package (you need to install the package `PkgDev` with `Pkg.add("PkgDev")`), but nowadays most package developers use https://github.com/attobot/attobot
